[dev] Review documentation
dojot/device-manager pull request #160
Opened 2020-09-17 13:55 UTC by eduardogmisiuk

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Docs update.

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
Removed the readthedocs documentation, transferring it to the README.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
https://github.com/dojot/dojot/issues/1584

* **Other information**:

2020-09-17 15:21 UTC, mprevide commented on README.md
> +  via AP, check its [documentation](https://dojot.github.io/device-manager/apiary_latest.html) for
via API

2020-09-17 22:06 UTC, thiagodpf submitted a review, later dismissed
:+1:

2020-09-18 17:04 UTC, thiagodpf submitted a review, later dismissed
:+1:

2020-09-18 18:36 UTC, mprevide commented on README.md
> +- `template.update` **deprecated**
At the end I don't know if we can say that really deprecated.... I think that not...

2020-09-18 18:36 UTC, mprevide commented on README.md
> +### **Event: `actuate`**
In my tests the event `actuate` doest exist, just the event `configure`

2020-09-18 18:36 UTC, mprevide commented on README.md
> +### **Event: `actuate`**
`{"event": "configure", "data": {"attrs": {"t": "100"}, "id": "19c216"}, "meta": {"service": "admin", "timestamp": 1600453556258}}`

2020-09-18 18:36 UTC, mprevide commented on README.md
> +### **Event: `actuate`**
To send a msg to device I use:

```sh
curl -X PUT \
    http://localhost:8000/device/19c216/actuate \
    -H "Authorization: Bearer ${JWT}" \
    -H 'Content-Type:application/json' \
    -d '{"attrs": {"t" : "100"}}'
```

2020-09-18 20:54 UTC, mprevide commented on README.md
> +```json
I think you can remove that example block and leave only the next one.

2020-09-18 20:57 UTC, mprevide requested changes
I left one more comment
And don't forget about release/v0.5.0

2020-09-21 13:52 UTC, thiagodpf approved these changes

2020-09-21 15:10 UTC, mprevide approved these changes
:smile_cat:

2020-09-23 14:06 UTC, mprevide approved these changes

2020-09-23 16:42 UTC, canattofilipe approved these changes

2020-09-23 17:02 UTC, merged