[0.4.4] - Refresh "updated" column of template every time template structure changes
dojot/device-manager pull request #168
Opened 2020-09-25 18:41 UTC by canattofilipe

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Service improvement

* **What is the current behavior?** (You can also link to an open issue here)
The column "updated" of the template table only is refreshed when the templates table changes, it is done by SQLAlchemy ORM framework (visit the class DeviceTemplate for more details)

* **What is the new behavior (if this is a feature change)?**
The column "updated" of the templates table is refreshed every time itself or its related table attrs changes. 

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No, it doesn't

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
No, there isn't

* **Other information**:
https://github.com/dojot/dojot/issues/1729

2020-09-28 13:34 UTC, mprevide requested changes
I'm not sure about that going to 0.4.4, I think it's not a good idea.

2020-09-28 14:28 UTC, canattofilipe commented
> I'm not sure about that going to 0.4.4, I think it's not a good idea.

Ok, so I will close it.

2020-09-28 15:13 UTC, mprevide commented
> > I'm not sure about that going to 0.4.4, I think it's not a good idea.
> 
> Ok, so I will close it.

This is not just my decision... I think you can discuss it with other people...
@canattofilipe

2020-09-30 14:23 UTC, canattofilipe commented
> > > I'm not sure about that going to 0.4.4, I think it's not a good idea.
> > 
> > 
> > Ok, so I will close it.
> 
> This is not just my decision... I think we can discuss it with other people...
> @canattofilipe

Hmm OK, So there goes my opinion, the `device-manager `service is one of the dojot's core service, so every change on it should be reviewed carefully and then covered by E2E tests by QA team. 

This PR introduces a very simple fix in order to keep template's "updated" attribute up to date after structure changes (for example add new attribute or remove a meta-attribute), this service are being used without this fix for a long time and none issue was registered, so in my opinion we can be conservative and  available it only in 0.5.0 version.

2020-10-02 12:05 UTC, closed without merging