[Device_manager] Fix: correção do filtro
dojot/device-manager pull request #198
Opened 2022-07-29 16:37 UTC by MarceloPimentel050975

* **Please check if the PR fulfills these requirements**
- [ x] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
dojot/dojot #2419

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:

2022-08-01 11:51 UTC, Huakson requested changes

2022-08-01 11:51 UTC, Huakson commented on DeviceManager/DeviceHandler.py
> +                page = page.join(DeviceTemplateMap, isouter=True)
Assim como reportado pelo codecov, é interessante ter um novo caso de teste que cubra esse novo comportamento.

2022-08-02 01:34 UTC, rodrigoaasm approved these changes
Approved! Congratulations on your first PR.

2022-08-02 13:04 UTC, Huakson approved these changes

2022-08-03 19:09 UTC, merged