[DOJOT-75] [DOJOT-76] Feature - Unique Labels
dojot/device-manager pull request #201
Opened 2022-08-12 20:22 UTC by LuanEdCosta

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
You can create multiple devices and templates with the same label

* **What is the new behavior (if this is a feature change)?**
Now the label of devices and templates are unique.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Yes.
1. Delete or rename all devices and templates with repeated labels  
2. Apply new migrations on existing databases

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
https://dojot.atlassian.net/browse/DOJOT-75
https://dojot.atlassian.net/browse/DOJOT-76

2022-08-18 17:49 UTC, LuanEdCosta commented
The CI stuck and I don't know why. 
I think I need some help here to run the CI or to run tests locally to check if everything is fine.

2022-08-24 15:45 UTC, rodrigoaasm requested changes
Insufficient unit test coverage.

2022-09-01 16:36 UTC, luisfelipefurlan approved these changes

2022-09-02 12:20 UTC, MarceloPimentel050975 approved these changes

2022-09-02 17:06 UTC, rodrigoaasm approved these changes
Ok

2022-09-02 17:08 UTC, merged