[DOJOT-141] [DOJOT-143] Create device with on or off state.
dojot/device-manager pull request #205
Opened 2022-11-07 20:17 UTC by ademirr

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

feature

* **What is the current behavior?** (You can also link to an open issue here)

can not disabled device

* **What is the new behavior (if this is a feature change)?**

now device can be disabled

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

yes

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

https://dojot.atlassian.net/browse/DOJOT-141
https://dojot.atlassian.net/browse/DOJOT-143

* **Other information**:

2022-11-10 16:41 UTC, LuanEdCosta approved these changes

2022-11-18 17:38 UTC, rodrigoaasm requested changes
All tests sent a request with disabled=false.

2022-11-21 18:31 UTC, LuanEdCosta commented
I tested if all existing devices would be enabled when upgrading the database with the `disabled` field. And it worked.

![image](https://user-images.githubusercontent.com/36794274/203132617-ab6cd042-5e12-4c36-97c2-4b223ce9bf75.png)

2022-11-21 18:32 UTC, LuanEdCosta approved these changes

2022-11-22 14:31 UTC, rzanetti-cpqd commented on tests/test_device_handler.py
> +                    self.assertEqual(result['devices'][0]['label'], 'test_device')
Acho que aqui precisa dar um assert de que o campo 'disabled' tá sendo retornado e contém o valor True

2022-11-22 15:50 UTC, LuanEdCosta commented on tests/test_device_handler.py
> +                    self.assertEqual(result['devices'][0]['label'], 'test_device')
O teste dá erro se fizer isso (cheguei a testar). Acho que é tudo mockado esses valores de retorno.

2022-11-22 16:12 UTC, rzanetti-cpqd commented on tests/test_device_handler.py
> +                    self.assertEqual(result['devices'][0]['label'], 'test_device')
Verdade! Não tinha reparado.
Sendo asism, na verdade agora eu não tô vendo nem sentido desse teste, pq pareque que tá um curto-cirtuito testando só o que tá mockado

2022-11-22 16:35 UTC, rzanetti-cpqd approved these changes
Como o Rodrigo comentou, faltam testes pra validar o comportamento de criar como desabilitado.
A parte da escrita em banco teria que ser feita via teste de integração, mas como sugerido pelo Luan vale criar ticket pra tratarmos isso no futuro.

Vou aprovar pra darmos vazão nessa feature, já que a funcionalidade está ok

Fica como tarefa imediata pelo menos implementar que uma chamada que chega na API com o valor 'true' em disabled vai propagar esse true até a parte que irá fazer a escrita no banco (ainda que a escrita em si esteja mockada)

2022-11-22 17:57 UTC, rodrigoaasm requested changes

2022-11-22 19:24 UTC, LuanEdCosta approved these changes

2022-11-22 19:32 UTC, rodrigoaasm approved these changes
Approved!

2022-11-22 19:33 UTC, merged